import type { Metadata } from "next";
import { Hind, Archivo_Black, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


const hind = Hind({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  variable: "--font-display",
  weight: "400",
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full","antialiased",hind.variable,archivoBlack.variable,geistMono.variable,"font-sans")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
